### ISSUE TITLE
Cursor displays incorrect time

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#11]
When I playback a recording and then crop the recording, the time label on the cursor is incorrect. Every thing else functioned fine; I was able to save, Crop, transcribe, and save recordings without issues. 

iPhone 7, safari 13.6

![2D03D4EA-0F79-4C75-9F06-1D915AB17CF8](https://user-images.githubusercontent.com/54418192/89131154-a84f1180-d4d8-11ea-8a96-38529c42f212.png)
![DC4B264C-4226-44FC-A42A-6B2A7C67A3BB](https://user-images.githubusercontent.com/54418192/89131155-a84f1180-d4d8-11ea-9700-9e8fce462a90.png)

**Comment by lorenachipstudio** [comment]
@koppen152 Thank you for reporting this-- we'll take a look and provide an update shortly.

**Comment by lorenachipstudio** [comment]
@koppen152 Code has been updated on staging for this, can you confirm it's resolved?

**Comment by koppen152** [comment]
@lorenachipstudio resolved.
