### ISSUE TITLE
scrapbook clips keep playing when I leave the scrapbook

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#12]
I played a clip from my scrapbook and then navigated out of the scrapbook to "Say What?" without stopping the clip. The clip kept playing while I played "Say What?" I was expecting the clips to stop playing automatically when I left the scrapbook.

iPhone 7 /Safari / iOS 13.6

**Comment by lorenachipstudio** [comment]
@koppen152 We'll take a look and provide an update

**Comment by lorenachipstudio** [comment]
Hi @koppen152 this should be resolved on staging now. Can you confirm when you get a chance?

**Comment by koppen152** [comment]
Fixed, thank you.
