### ISSUE TITLE
icons don't work

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#13]
after I make a recording, I can type in the "icon" box but no icon choices appear. Words and emojis I enter in the box are not saved. This happened on my iphone (iPhone 7, Safari, iOS 13.6)

This was not an issue from my laptop (Windows 10, Chrome 83)

**Comment by lorenachipstudio** [comment]
@koppen152 we'll take a look and provide an update

**Comment by lorenachipstudio** [comment]
@koppen152 This should be fixed on staging, can you confirm?

**Comment by koppen152** [comment]
@lorenachipstudio yes, the icons are working now. Thank you.
