### ISSUE TITLE
confusing error message - string_no_spaces

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#14]
When I enter a nickname that contains a space in "my family," I get the error message "String.no_spaces contains spaces."

Is it possible to change this to something more user-friendly, like "Please enter a nickname with no spaces"

This occurs on all my devices (iPad 7, Iphone 7/Safari 13.6, Windows Chrome 83)

**Comment by alexchippendale** [comment]
This should now be fixed in staging, please verify when you get a chance. Thanks!

**Comment by koppen152** [comment]
Fixed! Thank you!
