### ISSUE TITLE
avatar does not display in scrapbook

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#16]
I went to "Settings" to add an avatar for myself. When I tag myself in recordings, my avatar does not appear in my recordings, it's still the circle that says "me." The avatars for my family members appear in the appropriate recordings in the scrapbook.

iPhone 7 / Safari / iOS 13.6
Windows 10 / Laptop / Chrome 83

**Comment by alexchippendale** [comment]
This should now be fixed in staging. Please confirm when you get a chance, thanks!

**Comment by koppen152** [comment]
Yes, fixed. Thank you!
