### ISSUE TITLE
nothing happens when I search in the scrapbook

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#17]
When I type a word in the search bar in my scrapbook and click "Search," I expect the scrapbook to show only the clips/conversations that contain that word in the comment/transcription. Instead, nothing happens when I click "Search" and I continue to see all the clips/conversations. I confirmed that the word I was searching for did appear in the transcription of at least one clip.

**Comment by ythuang123** [comment]
I replicate this bug too. I'm searching based on text I entered in the description box, but nothing pulls up. 

Browser / Chrome

OS / Window 10 Enterprise v. 1909 (OS build 18563.959)

device / ThinkPad X1 Carbon 4G

**Comment by lorenachipstudio** [comment]
@koppen152 @ythuang123 We've deployed a fix onto the staging site for this. Can you confirm that the bug has been fixed?

**Comment by koppen152** [comment]
@lorenachipstudio Fixed for me! iPhone 7, safari, iOS 13.6

**Comment by ythuang123** [comment]
Works for me too! Thanks! Chrome / Window 10 Enterprise v. 1909 (OS build 18563.959) / ThinkPad X1 Carbon 4G
