### ISSUE TITLE
Version 8.2 appears twice under "Version History"

### ISSUE THREAD

**Issue by ichimura-a** [jkhartshorne/KidTalkIssues#18]
Not a bug per se, but Version 8.2 appears twice under different descriptions.
MacBook Air / Chrome Version 84.0.4147.105 / macOS Catalina Version 10.15.6

<img width="596" alt="Screen Shot 2020-08-03 at 1 54 15 PM" src="https://user-images.githubusercontent.com/68654587/89212189-0b9c7a80-d591-11ea-92ad-051a9c04ac8d.png">

**Comment by Abbyrosler** [comment]
I noticed this too
Chrome 83; Macbook Pro (version 10.13.6); macOS High Sierra

**Comment by lorenachipstudio** [comment]
@ichimura-a @Abbyrosler this should be fixed on staging- can you confirm?

**Comment by ichimura-a** [comment]
@lorenachipstudio This is fixed for me.
