### ISSUE TITLE
Conversations in Scrapbook can't be edited

### ISSUE THREAD

**Issue by ichimura-a** [jkhartshorne/KidTalkIssues#19]
The details for conversations cannot be edited as there is no pencil symbol.

MacBook Air / Chrome Version 84.0.4147.105 / macOS Catalina Version 10.15.6
![image](https://user-images.githubusercontent.com/68654587/89227875-78713e00-d5ac-11ea-99b5-9ece5f0e37d2.png)

**Comment by lorenachipstudio** [comment]
@ichimura-a We've deployed a fix onto the staging site for this. Can you confirm that the bug has been fixed?

**Comment by ichimura-a** [comment]
Yes, I am able to edit conversations in my Scrapbook. Thank you!
