### ISSUE TITLE
Misspelling on invite email

### ISSUE THREAD

**Issue by ythuang123** [jkhartshorne/KidTalkIssues#20]
This is minor, but the invitation email has a misspelling (on "address"). 

You have recently been invited to KidTalk! You can sign up for an account with this email addres

Chrome, Window 10 Enterprise v. 1909 (OS build 18563.959), ThinkPad X1 Carbon 4G

**Comment by lorenachipstudio** [comment]
@ythuang123 We'll take a look- thank you!

**Comment by lorenachipstudio** [comment]
@ythuang123 We've deployed a fix onto the staging site for this. Can you confirm that the bug has been fixed?

**Comment by ythuang123** [comment]
Yep, this has been fixed! Thanks!
