### ISSUE TITLE
Scrapbook; 'Search for phrase' filter does not yield results 

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#22]
When I enter keywords/ phrases into the "Search for phrase" bar, nothing happens after I click "search". All the clips remain in view without adhering to the keywords.

Chrome 83; Macbook Pro (version 10.13.6); macOS High Sierra

**Comment by lorenachipstudio** [comment]
@Abbyrosler We'll take a look- thank you!

**Comment by lorenachipstudio** [comment]
@Abbyrosler We've deployed a fix onto the staging site for this. Can you confirm that the bug has been fixed?

**Comment by Abbyrosler** [comment]
@lorenachipstudio Confirmed!
