### ISSUE TITLE
Can't successfully submit a comment on clip

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#23]
When I click "+ comment" on a clip, the "Add comment" block pops up, I type in my comment, but when I press "submit" nothing happens. The "Submit" button remains outlined in blue, but no comment is saved.

Chrome 83; Macbook Pro (version 10.13.6); macOS High Sierra

**Comment by lorenachipstudio** [comment]
@Abbyrosler We'll take a look- thank you!

**Comment by lorenachipstudio** [comment]
@Abbyrosler Are you able to provide the following:

1. Send a series of screen shots, or step by step information with details to recreate it?
2. Is this only on that one clip, a few clips or all clips in your scrapbook?

**Comment by Abbyrosler** [comment]
@lorenachipstudio I tried it again and it worked this time with multiple clips! This needs no fix until further notice. Thanks!

**Comment by jkhartshorne** [comment]
Sounds like this may be the same as this one: https://github.com/jkhartshorne/KidTalkIssues/issues/31

@Abbyrosler - was this right after you made a new account?

**Comment by alexchippendale** [comment]
@Abbyrosler @jkhartshorne This was related to an error when no name or avatar had been selected for some new accounts. This is the same issue as #31 , please close this issue when #31 is confirmed, thanks!
