### ISSUE TITLE
Consent form; Checkbox goes from white square to blue square

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#24]
While I expected the checkbox to go from light grey square (unchecked) to dark grey square (checked), it goes from white square (unchecked) to blue square (checked).

Chrome 83; Macbook Pro (version 10.13.6); macOS High Sierra

**Comment by koppen152** [comment]
@Abbyrosler This is probably just the bug checking checklist being not up to date. Thanks for your attention to detail though!

**Comment by ichimura-a** [comment]
Yes, that is totally my mistake not updating the bug checking checklist. Sorry about that. This issue can be closed.
