### ISSUE TITLE
Overlap of buttons

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#26]
**What I expect**: the play button to not overlap with text

**Me**
* Chrome Version 84.0.4147.105
* MacBook Air
* OSX 10.15.6

I've seen a similar error on my Galaxy S20 as well.

![Screen Shot 2020-08-05 at 2 25 57 PM](https://user-images.githubusercontent.com/6118115/89450163-1c332900-d728-11ea-9655-5e4c30cf7fcc.png)

**Comment by lorenachipstudio** [comment]
@jkhartshorne We'll take a look- thanks!

**Comment by lorenachipstudio** [comment]
@jkhartshorne Fix was deployed to staging. Can you confirm the fix?

**Comment by jkhartshorne** [comment]
Fixed!
