### ISSUE TITLE
User does not automatically disappear under "Access to [child]'s clips" when invitation is deleted

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#28]
In the 'My Family' tab, I invited a user to access the child's clips. When I clicked the 'Edit' option under "Access to child's clips" and then **"Delete this Invitation",** the user does NOT disappear under "Access to child's clips". If I refresh the page, then that user disappears, but I _have_ to refresh the page in order to see that. 

Safari 13; iOS 13.5.1; iphone 8

**Comment by alexchippendale** [comment]
@Abbyrosler Thank you for bringing this to our attention. The invitation is deleted on the backend upon clicking "Delete this Invitation", but as you noted there is no immediate user feedback to make that clear. We are currently working on building this user feedback into the app. Thanks!

**Comment by alexchippendale** [comment]
@Abbyrosler we are continuing to work on this. We'll let you know when a fix is up.

**Comment by alexchippendale** [comment]
@Abbyrosler This should be fixed on staging. Please confirm when you get a chance!

**Comment by Abbyrosler** [comment]
@alexchippendale Confirmed!
