### ISSUE TITLE
Saving recordings doesn’t always work

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#3]
Pressing ‘save clip’ during initial playback will sometimes result in getting stuck. The upload indicator sticks at 100%, but nothing is saved. Note that starting a new recording doesn’t reset the ‘save clip’ button. It’ll be stuck showing ‘100%’ and being nonfunctional until you refresh the browser.

**Observed Devices**
Chrome/Galaxy
Samsung Internet / Galaxy
7/16 Chrome/MacBook Air
7/17 Chrome 83 / MacBook Air 10.14.6 (used in-app recording. Got stuck at 100% saved.)
7/14 safari/7th generation iPad (this issue remained when I refreshed my browser and made another recording. When I played it back, the name I had given the previous recording that would not save appeared in the transcription box and the submit clip button was grayed out and said 100%.)

**Not observed devices**
iPhone 7/safari
iPad/safari
Chrome/Ubuntu
Chrome/Galaxy S9
iPhone 10/Safari
MacBook Pro/Chrome

**Comment by koppen152** [comment]
I have not encountered this issue this week. IPhone 7/Safari/iOS 13.6

**Comment by ichimura-a** [comment]
I have also not encountered this issue this past week. MacBook Air/Chrome 84.0.4147.105/macOS 10.15.6

**Comment by parkerrobbins** [comment]
I have not observed this issue.

Galaxy S9 | Android 10 | Chrome 84.0.4147.115
Dell Latitude E7450 | Ubuntu 18.04.4 LTS | Chrome 84.0.4147.105

**Comment by jkhartshorne** [comment]
OK. I'm closing.

**Comment by julianividal** [comment]
I had this problem on the **live site** on August 11th on a Macbook Pro, running Chrome 84.0.4147.105 on MacOS 10.14. I checked again today (08/19) and it still occurs.

**Comment by jkhartshorne** [comment]
@lorenachipstudio FYI

**Comment by koppen152** [comment]
I just uploaded a 6-second video to the staging site and it did not appear in my scrapbook after I pressed “submit clip.” I did it a second time and it worked that time. 
IPhone 7, safari 13.6.1

**Comment by alexchippendale** [comment]
This should be fixed in production now.
