### ISSUE TITLE
"Parent Avatar" -> "Adult Avatar"

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#30]
When you add an adult to your family, it asks you to pick a "parent avatar". Please change to "adult avatar" or just "avatar". Not all of these are meant to be adults!

**Comment by alexchippendale** [comment]
@jkhartshorne We are currently working on this. Is a deploy to staging once it's done alright? Or is it important that it's on production as soon? Thanks

**Comment by jkhartshorne** [comment]
Deploy to staging is fine.

**Comment by alexchippendale** [comment]
Great, I'll let you know when it's up.

**Comment by alexchippendale** [comment]
@jkhartshorne This should be fixed on staging now, it is now just "avatar" instead of "parent avatar". Please confirm when you get a chance, thanks!

**Comment by alexchippendale** [comment]
@jkhartshorne This should be fixed on staging with just "avatar". Please confirm and close when you get a chance, thanks!
