### ISSUE TITLE
Comment button gets stuck

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#31]
**What Happens** Unable to click "submit".
**What I Expect** To be able to submit a comment!

![Screen Shot 2020-08-09 at 9 38 00 AM](https://user-images.githubusercontent.com/6118115/89733554-2e60e000-da24-11ea-811e-190cb31e53b5.png)

This has happened twice to me. Both times with brand new accounts. For the first account, I submitted an error through the app itself, and then afterwards I was able to make a comment. 

For the second account, I tried doing the same thing (submitting an issue), but that did not enable me to submit comments. I have tried reloading, using various other functions on the account, different content for the comments, all with no effect. I still can't make a comment.

**Comment by alexchippendale** [comment]
@jkhartshorne Thanks for the detail here, sounds like it can happen with new accounts sometimes. We are currently working on recreating this issue.

**Comment by alexchippendale** [comment]
@jkhartshorne The button should now no longer get stuck in this case. Please confirm when you get a chance (might want to clear your cache to make sure).

**Comment by jkhartshorne** [comment]
Seems to work!
