### ISSUE TITLE
Processing audio is prohibitively slow

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#33]
Having all the processing happen before playback solved one problem, but it seems it has created another. Processing takes a very, very long time. For in-app recordings, it looks like it usually takes longer to process than to record. So someone making a 2-minute recording may wait 2.5 minutes for processing, which is too long, particularly if we expect them to stick around to label the recording once processing is complete. Processing for uploads is faster but still quite slow. 

[Here](https://docs.google.com/spreadsheets/d/1VBkhsQzyk5brgE5gXdnmh7aMFtC3ZFoy_-6l7HYDhJg/edit#gid=0) are our timing tests. 

It would be best if this could be sped up somehow. If not, though, I think we need to change the workflow so that they can label and save immediately. Any cropping or making snippets would have to happen later, through the scrapbook function.

**Comment by alexchippendale** [comment]
@jkhartshorne Thanks for the detailed information on timing. Could you take a look at #25 , I believe these may be the same issue. The difference being in issue #25 the clips are sometimes even longer uploads and people could end up exiting out. If they seems like the same issue, we should combine these two tickets. Thanks!

**Comment by ythuang123** [comment]
@alexchippendale -- I think (not totally sure) that this is also related to issue #2. So I'm on the staging site on my PC (Lenovo, Chrome, Windows) and I made another 23-minute recording. After I pressed stop, it took a long time to convert -- but it did do it eventually. But then after I press submit, it was stuck on the uploading screen for 60+min, and then I exited out. When I go to the scrapbook, I see the grayed out tile. Pics below.
![image](https://user-images.githubusercontent.com/68764650/89943925-01abf480-dbed-11ea-9d6c-d594c0b6fc55.png)
![image](https://user-images.githubusercontent.com/68764650/89943977-18524b80-dbed-11ea-967f-24715cc83caa.png)

**Comment by alexchippendale** [comment]
@ythuang123 Thanks, upload times and clip length do seem to be a common factor on the grayed tiles. We're working on seeing if the two are related.

**Comment by jkhartshorne** [comment]
@alexchippendale These could be related. I wouldn't be surprised if getting stuck in processing was related to people exiting out or their phone going to sleep. Even if it isn't related, though, it's an issue in its own right, since it affects usability. Nobody wants to wait a few minutes on the same page waiting for the file to upload. 

Adding a status bar may be helpful BOTH for UX and also for debugging.

**Comment by jkhartshorne** [comment]
Tagging https://github.com/alexchippendale/KidTalkRemainingTasks/issues/19

**Comment by jkhartshorne** [comment]
@alexchippendale So looking at the spreadsheet, it looks like processing of in-app recordings is very fast on iPhone (7, 8, & XR). It's slow on everything else we've tested. Do you have any idea why? Does that mean we can have fast processing on all platforms? Or is there just something special about iPhones?

**Comment by alexchippendale** [comment]
@jkhartshorne Each device + browser combo has its own way of processing audio, which has a lot to do with it. We've got it going faster for iPhone + Safari, and are testing different options to get it faster with other combinations. The new flow should help the user experience as we investigate ways to speed up converting and processing times for other devices. Also, when we complete the native app versions, we should be able to tap into native device functionality which generally has more accelerated audio processing.

**Comment by jkhartshorne** [comment]
@alexchippendale - makes sense. Thanks for letting me know.
