### ISSUE TITLE
No time stamp on cropping bar

### ISSUE THREAD

**Issue by ythuang123** [jkhartshorne/KidTalkIssues#34]
I recorded live (about 2 minutes) and was expecting an end timestamp on the cropping bar. Instead I got 0.0 for both start and end.

Browser / Chrome, OS / Window 10 Enterprise v. 1909 (OS build 18563.959), device / ThinkPad X1 Carbon 4G

![2020-08-12_10-15-12_000](https://user-images.githubusercontent.com/68764650/90027527-a3cbeb00-dc86-11ea-9b76-5a9266b4a9a3.png)

**Comment by lorenachipstudio** [comment]
@ythuang123 I'll have the team take a look at this. I'll keep you posted on updates.

**Comment by alexchippendale** [comment]
@ythuang123 We've tested this quite a bit and have not yet been able to recreate it. Is there a series of steps you've done that reliably produce the 0.0 issue? Also does this only happen on one device or across different devices? Thanks!

**Comment by ythuang123** [comment]
@alexchippendale -- This was the first time I'd seen it in my many times on the staging and production sites on my iPhone SE and Lenovo PC. If you can't reproduce it, I'm fine with chalking it up to a stochastic process. Thanks for checking it out.
