### ISSUE TITLE
Say What: Audio recordings are not of children talking

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#37]
The audio recordings seem to be of people in our lab talking. One was about using prescriptive rules, another about intuition, and another was actually one of my own recordings (where the "correct" transcription was ""). Again, NOT kid talk!

Chrome 83, macOS High Sierra, Macbook Pro Version 10.13.6

**Comment by alexchippendale** [comment]
@Abbyrosler See the thread in #9 , this is not a bug in the software, just the clips in the staging db that meet the threshold for Say What. This is lab user uploaded content, so we can't control what they put as transcriptions or who is talking in the clip. Let me know if that makes sense!

**Comment by Abbyrosler** [comment]
@alexchippendale ahh got it! I must have looked past that one. Thank you!
