### ISSUE TITLE
[Start a Conversation] Repeating images

### ISSUE THREAD

**Issue by parkerrobbins** [jkhartshorne/KidTalkIssues#4]
### Date 
2020-07-23

### Browser / OS / device (including version numbers)
Google Chrome Version 84.0.4147.89 (Official Build) (64-bit), Ubuntu 18.04.4 LTS, Dell Latitude E7450

### What did you do?
Refreshed the **Start a Conversation** feature 10 times.

### What did you expect to happen?
I expected to see different images each time.

### What did happen?
Image 2 and 4 out of the series were the same.

### Visual Evidence (screenshots, videos, text)
Image 2:
![img2](https://user-images.githubusercontent.com/31826170/88332557-be9ce680-ccfc-11ea-8bad-8a1f9846bb3a.png)

Image 4:
![img4](https://user-images.githubusercontent.com/31826170/88332564-c2c90400-ccfc-11ea-8d33-02e2e62ad478.png)

### Severity/Priority
Moderate

**Comment by lorenachipstudio** [comment]
@jkhartshorne 

Hi Josh, 

The team looked through this and found no bugs. 

We're not sure if the user is aware that the images seen in that section are randomly selected from a pool of about 50 images. If you refresh enough times you should expect to see the same image twice on occasion. It is intended to work this way. 

It sounds like they are assuming that you will only ever see images you've never seen before. Unfortunately that would cause issues of its own by limiting the possible images a child could see for parents with multiple kids and would mean eventually you wouldn't be able to use the "Start a Conversation" feature at all once the images run out. While it is possible to build it that way, it is not how it is currently built and we would recommend against it.

Please let me know if you have any other questions about this. 

Lorena
