### ISSUE TITLE
Audio recordings in scrapbook keep playing after "collapsing"

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#40]
If I click 'play' on an audio recording in my scrapbook, it will play from beginning to end (as it should!). However, once the audio reaches the end, and I tap the rectangle to collapse back into the scrapbook, the audio keeps playing out of my control.

Safari 13; iOS 13.5.1; iphone 8

**Comment by alexchippendale** [comment]
@Abbyrosler We can work on having the audio stop in either case if you close the scrapbook tile. Are you saying it played the same clip over again after it ended and you closed it, or that you had stopped listening part way through and closed it but it kept playing?

**Comment by Abbyrosler** [comment]
@alexchippendale It played the same clip over again after it ended and I closed it. In other words, when I opened the scrapbook tile and pressed "play", it would play from start to finish. But when I closed it, it started playing again from the beginning. I think the same thing would happen even if I stopped the clip midway. Please let me know if you need more clarification!

**Comment by alexchippendale** [comment]
Thanks @Abbyrosler that makes sense. We have someone working on it and we'll update you once we update staging with a fix. Thanks!

**Comment by alexchippendale** [comment]
@Abbyrosler we've deployed a fix for this on staging (if it doesn't work at first you may want to just clear your cache). Please test and verify when you get a chance!

**Comment by Abbyrosler** [comment]
@alexchippendale The fix is confirmed! Thanks.
