### ISSUE TITLE
Zip code error when creating new account part II

### ISSUE THREAD

**Issue by Abbyrosler** [jkhartshorne/KidTalkIssues#41]
I noticed @Ythuang123 reported this last week. The same thing just happened to me! Not sure why I am getting this error, and also there is a typo. 

<img width="1340" alt="uhoh" src="https://user-images.githubusercontent.com/69211699/90923739-3291e380-e3bc-11ea-9712-75dfe5fc48ae.png">

Macbook pro Version 10.13.6, macOS High Sierra, Chrome 83

**Comment by alexchippendale** [comment]
@Abbyrosler a fix for this has been deployed to staging.

**Comment by jkhartshorne** [comment]
@Abbyrosler can you please confirm that you no longer see this issue?

**Comment by Abbyrosler** [comment]
@jkhartshorne Confirmed.
