### ISSUE TITLE
Text after recording a conversation

### ISSUE THREAD

**Issue by ichimura-a** [jkhartshorne/KidTalkIssues#42]
After recording a conversation, the text above the play button said "Now let's play back and crop what was said in the recording.", even though the conversation couldn't be cropped.

MacBook Air / MacOS 10.15.6 / Chrome 84.0.4147.135
iPhone 7 / iOS 13.6.1 / Safari 13

![image](https://user-images.githubusercontent.com/68654587/91748503-121d1280-eb8e-11ea-8ed5-6e7f3f21d2fc.png)

**Comment by lorenachipstudio** [comment]
@ichimura-a We'll take a look and provide an update as soon as possible! Thank you.

**Comment by koppen152** [comment]
I ran into the same issue as @ichimura-a just now. I won’t add a screenshot because it looks the same as the image he included in his post. 

IPhone 7, Safari 13. 6.1

**Comment by alexchippendale** [comment]
@ichimura-a @koppen152 Yes, this is old copy text, we will be removing it.

**Comment by alexchippendale** [comment]
This has been updated on staging.
