### ISSUE TITLE
Clips or Snippets?

### ISSUE THREAD

**Issue by ichimura-a** [jkhartshorne/KidTalkIssues#43]
Are the recordings you extract from a conversation called "clips" or "snippets"? Is there a difference between them?

While on the scrapbook, recordings could be filtered by "Clip", but the button to create a clip/snippet is labeled as "Create Snippets". Then, while creating a clip/snippet, the transcription box was labeled as "Provide a transcription of this snippet:" while the button to submit it was labeled as "Extract Clip".

MacBook Air / MacOS 10.15.6 / Chrome 84.0.4147.135
iPhone 7 / iOS 13.6.1 / Safari 13

![image](https://user-images.githubusercontent.com/68654587/91749356-5957d300-eb8f-11ea-9fa6-2d2574ab68d1.png)
![image](https://user-images.githubusercontent.com/68654587/91749363-5bba2d00-eb8f-11ea-9b73-4ff8bcbe9f19.png)

**Comment by jkhartshorne** [comment]
Good catch. These should be snippets everywhere. @lorenachipstudio

**Comment by lorenachipstudio** [comment]
@jkhartshorne @ichimura-a I'll let the dev team know to make it snippets everywhere. I'll confirm when changes are in staging

**Comment by alexchippendale** [comment]
This has been updated on staging.
