### ISSUE TITLE
Logging in with Google

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#44]
I feel like it used to be possible to log in with different google account. Maybe I just remember wrong. But now, it automatically logs me in with whatever google account I happen to be logged into in my browser at the moment. I don't want to have to log out globally in order to use a different account. Can this be changed?

(I mean, I can also use an incognito tab. But I don't want to assume people know how to do that.)

**Comment by jkhartshorne** [comment]
Scratch that. Incognito doesn't seem to work. Probably a cookies problem.

**Comment by alexchippendale** [comment]
@jkhartshorne Unfortunately this is an issue with google's account authentication and login process. Google accounts can get finicky in this way. Here's one thread on a related problem: https://support.google.com/mail/thread/18368828?hl=en . I've experienced the same issue between my google accounts on YouTube and other google platforms.

You may be able to use this from google: https://accounts.google.com/AccountChooser , but it is not something we have control over from our codebase.

**Comment by jkhartshorne** [comment]
Understood.
