### ISSUE TITLE
Say What? Stays paused instead of advancing

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#47]
If I submit my guess before the clip is done playing, the clip continues playing while I get the animation telling me I got it right. When the clip is done playing, the pause icon remains instead of the play button. I can press the pause button and it will convert to the play button and I can then press the play button to go on to the next clip. I’m not sure if this is a bug per se since it only happens when I play the game wrong. This happened 4/4 times when I submitted my guess before the recording was over, and it happened 0/5 times when I waited for the recording to finish before submitting my guess. 

IPhone 7, safari, iOS 13.6.1

**Comment by lorenachipstudio** [comment]
@koppen152 thanks for letting us know-- we'll take a look and provide an update asap.

**Comment by parkerrobbins** [comment]
Reproduced: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit), Ubuntu 20.04.1 LTS, Dell Latitude E7450

**Comment by alexchippendale** [comment]
@koppen152 @parkerrobbins This has been fixed and deployed to staging.

**Comment by parkerrobbins** [comment]
Yep, fixed for me! Thanks for letting us know, @alexchippendale.

**Comment by koppen152** [comment]
@alexchippendale fixed for me too! Closing this issue. Thank you!
