### ISSUE TITLE
File recorded in KidTalk 'has limited support' when I go to extract a snippet

### ISSUE THREAD

**Issue by parkerrobbins** [jkhartshorne/KidTalkIssues#48]
**Date**
2020-09-01

**Browser / OS / device**
Google Chrome Version 85.0.4183.83 (Official Build) (64-bit), Ubuntu 20.04.1 LTS, Dell Latitude E7450

**What did you do?**
1. Make a short recording (10.4 sec) by clicking the *Spontaneous* button under **Record Conversation**.
2. Selected a speaker, provided a description, added an icon, marked as private, and submitted the conversation.
3. Went to my scrapbook and clicked *Create Snippet*.

**What did you expect to happen?**
I expected to see the soundwaves of the clip between the cropping bars.

**What did happen?**
Between the cropping bars reads, _This file type has limited preview support._

**Visual Evidence**
![filetype_has_limited_support](https://user-images.githubusercontent.com/31826170/91859995-16523a00-ec39-11ea-8526-337a72242469.png)

**Comment by parkerrobbins** [comment]
Can reproduce on the same machine / browser without doing any of the things in step 2 for a clip of similar length (except for submitting the conversation, obviously).

**Comment by parkerrobbins** [comment]
Can reproduce this on my phone as well. 

Chrome Version 85.0.4183.81 / Android 10 / Samsung Galaxy S9

![Screenshot_20200901-095950_Chrome](https://user-images.githubusercontent.com/31826170/91860842-2585b780-ec3a-11ea-8994-d1a9270939ff.jpg)

**Comment by koppen152** [comment]
Reproduced on my phone. IPhone 7, safari, iOS 13.6.1

**Comment by Abbyrosler** [comment]
*this happens to me too

<img width="1368" alt="Screen Shot 2020-09-01 at 11 43 55 AM" src="https://user-images.githubusercontent.com/69211699/91874672-7f8d7980-ec48-11ea-8f52-6b0137adb026.png">

Device: Macbook pro Version 10.13.6

OS: macOS High Sierra

Browser: Chrome 83

**Comment by alexchippendale** [comment]
This is placeholder text, we will be removing it. It has to do with what browsers are capable of showing for waveforms, not an issue with the recording. In some cases the waveform won't be available, but we'll remove the text so that it's not confusing.
