### ISSUE TITLE
Say What Clip Not Playing Completely

### ISSUE THREAD

**Issue by jmnolasco** [jkhartshorne/KidTalkIssues#5]
I'm not sure if this has to do with the fact that it was an audio clip extracted from a video, but when I was testing out Say What, a clip I had uploaded was not playing entirely. When I tried to pause it and replay, it went to a new clip.

Sometimes there are also lags for clips to play (e.g. I had to pause it and replay for it to start)
Tested on: iPhone XR, Safari browser

**Comment by lorenachipstudio** [comment]
@jmnolasco this should be resolved on staging- can you confirm?

**Comment by jmnolasco** [comment]
I just checked again, on iPhone XR, Safari, with a 30 second clip and it uploaded much faster for me, thank you so much!
