### ISSUE TITLE
"Submit" button on survey doesn't work

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#50]
MacBook Air, Chrome 

**What I did**
Answer a question and click 'submit'

**What I expected to happen**
Submission!

**What did happen**
Nothing for about 30 seconds. As I was typing in this issue, it finally loaded a different question. Not sure what to make of that.

![Screen Shot 2020-09-03 at 10 34 43 AM](https://user-images.githubusercontent.com/6118115/92129257-46ccdc00-edd1-11ea-8c8c-7b77155c1fd3.png)

**Comment by jkhartshorne** [comment]
Since then, it seems to be working, though it's still a bit sluggish? I think we should leave this open in case anyone else reports it, or it reoccurs for me.

**Comment by lorenachipstudio** [comment]
Hey @jkhartshorne we'll take a look and see if there's a problem/fix to this. Thanks!

**Comment by alexchippendale** [comment]
@jkhartshorne This could happen because of the server temporarily responding a little slower, an internet connection going a bit slower temporarily, or your device getting getting used to the new HTML and CSS of the build. We'll keep an eye on it, thanks for the info.
