### ISSUE TITLE
Snippets should default to same date as original

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#51]
Particularly since I can't see the date of the original while setting the date of the snippet!

**Comment by Abbyrosler** [comment]
Agreed! This can be confusing.

**Comment by lorenachipstudio** [comment]
@jkhartshorne will let the team know to see if we can make this change asap

**Comment by alexchippendale** [comment]
@jkhartshorne @Abbyrosler This is a good idea, I can see how that would be confusing. We'll start working on it!

**Comment by allieheyl** [comment]
When I saved my snippet today it defaulted to July 26 2020 as the date it was recorded

**Comment by jkhartshorne** [comment]
@lorenachipstudio

**Comment by alexchippendale** [comment]
@allieheyl Was that the date of the conversation it was based off? Or did you upload a video just before then with that date? Or is this a random date? Any amount of information would be helpful.

**Comment by allieheyl** [comment]
The video I uploaded during the bug check was from July 25th, but the snippet I made was based on a recording I had just made yesterday and I had deleted the uploaded recording prior to this.

**Comment by alexchippendale** [comment]
Thanks for the info!

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging for verification.

**Comment by jkhartshorne** [comment]
@alexchippendale looks like it works. Please push to production.

**Comment by alexchippendale** [comment]
This should be deployed to production this week.

**Comment by alexchippendale** [comment]
This has been deployed to production!
