### ISSUE TITLE
August appears twice in scrapbook

### ISSUE THREAD

**Issue by parkerrobbins** [jkhartshorne/KidTalkIssues#52]
**Date**
2020-09-03

**Browser // OS // Device**
- Google Chrome Version 85.0.4183.83 // Ubuntu 20.04.1 LTS // Dell Latitude E7450
-  Chrome 85.0.4183.81 // Android 10 // Samsung Galaxy S9

**What did you do?**
Navigated to my scrapbook.

**What did you expect?**
I expected to see my conversations and snippets organized by month.

**What did happen?**
I saw two August 2020 sections.

**Visual Evidence**

![Screenshot_20200903-110117_Chrome](https://user-images.githubusercontent.com/31826170/92132262-ef306f80-edd4-11ea-9868-cf2c43bbc3d8.jpg)

![image](https://user-images.githubusercontent.com/31826170/92132596-58b07e00-edd5-11ea-9d64-8fc4ffee251a.png)

**Comment by lorenachipstudio** [comment]
@parkerrobbins we'll take a look and fix this- thank you!

**Comment by alexchippendale** [comment]
@parkerrobbins Did this happen after submitting a conversation / snippet, or when you got into the scrapbook upon opening the app? Or does this occur every time you're in the scrapbook?

**Comment by parkerrobbins** [comment]
@alexchippendale Every time I enter the scrapbook (doesn't matter how). I only noticed the issue today, though, so I'm not sure how long it has been going on.

**Comment by alexchippendale** [comment]
@parkerrobbins Thanks, that should help us debug it.

**Comment by alexchippendale** [comment]
@parkerrobbins Could you send over the dates of the first and last tiles in both August 2020 sections you're seeing, and any other details about those tiles if possible. We've had trouble recreating this issue locally and that information may allow us to replicate it. Thanks!

**Comment by jkhartshorne** [comment]
@parkerrobbins -- can you please follow up on this?

**Comment by parkerrobbins** [comment]
@alexchippendale @jkhartshorne 

Apologies that I missed this. The issue is now resolved in my scrapbook.
