### ISSUE TITLE
"February" is misspelled

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#53]
When setting a kid's age, it's "Feburary". 

@lorenachipstudio

**Comment by lorenachipstudio** [comment]
@jkhartshorne we'll get this fixed asap

**Comment by alexchippendale** [comment]
This will be brought into one of the next updates that includes #54.

**Comment by alexchippendale** [comment]
@jkhartshorne This has been deployed to staging along with other fixes.

**Comment by alexchippendale** [comment]
This should be deployed to production this week.

**Comment by alexchippendale** [comment]
This has been deployed to production.
