### ISSUE TITLE
Admin page seems to be broken

### ISSUE THREAD

**Issue by jkhartshorne** [jkhartshorne/KidTalkIssues#55]
This was working relatively recently.

**What I expect**
To see a list of users on the admin page

**What I actually see**
An empty table

![Screen Shot 2020-09-07 at 4 43 19 PM](https://user-images.githubusercontent.com/6118115/92415995-5e85c680-f129-11ea-9b42-f8dbc48288c7.png)

**Comment by lorenachipstudio** [comment]
@jkhartshorne we'll take a look at this and provide an update asap.

**Comment by SecondStreetDevelopment** [comment]
@jkhartshorne, apologies for the trouble, I'm looking into this now.  I'll let you know when I have it fixed.

**Comment by SecondStreetDevelopment** [comment]
@jkhartshorne, we've identified a fix for this.  We will be deploying it to production very soon.  I will let you know when it goes live.

**Comment by SecondStreetDevelopment** [comment]
We should have this deployed to production today. We will update when the deploy is complete.

**Comment by SecondStreetDevelopment** [comment]
This admin page fix has been deployed to production, you should be able to see users in the table now.

**Comment by jkhartshorne** [comment]
@SecondStreetDevelopment 

Staging now works for me, but I don't see any difference in production.

**Comment by SecondStreetDevelopment** [comment]
You're correct, I think the emergency patch Alex just deployed removed this fix.  I'll request Alex do a redeploy to production with this fix and the patch included.

**Comment by alexchippendale** [comment]
Production has now been re updated with this fix.

**Comment by jkhartshorne** [comment]
A month or so ago we had maybe a dozen users with "eligible" clips. Now, only 2. Do you know what happened?

**Comment by SecondStreetDevelopment** [comment]
I'm not sure what could've happened, perhaps just an error in how we're filtering eligibility?  I can run a manual query using the eligibility criteria and take a look at what's returned.  That may shed some light.

**Comment by jkhartshorne** [comment]
Are you only including snippets now? Because I think all old recordings
were automatically turned into conversations, regardless of length. If you
are excluding conversations, that might be why all older recordings are
excluded.

**Comment by SecondStreetDevelopment** [comment]
Yes, I think that may be it. I'm testing a fix for this right now.

**Comment by SecondStreetDevelopment** [comment]
Fix confirmed.  I've committed this fix to our Github repository.  I'm publishing to the staging site now.  This fix should be published to the production site later this week.

**Comment by alexchippendale** [comment]
This has been deployed to production!
