### ISSUE TITLE
Messages page not displaying

### ISSUE THREAD

**Issue by parkerrobbins** [jkhartshorne/KidTalkIssues#58]
@jkhartshorne @lorenachipstudio 

**Date**
2020-09-24

**Browser / OS / device (including version numbers)**
Google Chrome Version 85.0.4183.121 (Official Build) (64-bit), Ubuntu 20.04.4 LTS, Dell Latitude E7450

**What did you do?**
Went to the menu in the sidebar and clicked on *Message from the scientists*.

**What did you expect to happen?**
I expected to see *Review the updates from the scientists building KidTalk* followed by a list of articles, as I see on my phone and as I have seen in the past.

**What did happen?**
No list of articles appears. Refreshing doesn't help. (No problem on my phone, though.)

**Visual Evidence (screenshots, videos, text)**
![messages](https://user-images.githubusercontent.com/31826170/94160843-10740100-fe53-11ea-9ae5-ea1547c9c33d.png)

**Comment by ichimura-a** [comment]
Also happened to me

iPhone 7 / Safari 13 / iOS 13.7

![image](https://user-images.githubusercontent.com/68654587/94163440-db1ce280-fe55-11ea-8b89-1820f1091d6b.png)

**Comment by alexchippendale** [comment]
@parkerrobbins Can you try closing your developer console, navigating using the sidebar to another page like recording or scrapbook, and use the menu again to navigate back to the messages page?

@ichimura-a Can you do the same (don't worry about the dev console stuff), navigate to another page via the menu and navigate back?

Let me know if you guys are able to see the messages then, sometimes the dev console or caching can cause some weirdness.

**Comment by ichimura-a** [comment]
@alexchippendale The page displays properly now when I reload it. I also navigated to another page and navigated back, and the page displayed properly as well.

**Comment by parkerrobbins** [comment]
@alexchippendale Hmm, it's working now for me, too. I guess we can close this. 

(By the way, I only opened the developer tools in case it was helpful for you. It wasn't displaying with or without them open.)

**Comment by alexchippendale** [comment]
@parkerrobbins I see. Thank you, the dev console is often very helpful for us to see like that when debugging! I wasn't sure if you had it opened the whole time or if you just opened it to show the logs.

**Comment by parkerrobbins** [comment]
@alexchippendale Yeah, just to show the logs. I'm somewhat of a programmer, so I generally have a vague idea of what might be helpful. Glad it actually is! :slightly_smiling_face:
