### ISSUE TITLE
Share invitation doesn't send email

### ISSUE THREAD

**Issue by ythuang123** [jkhartshorne/KidTalkIssues#6]
I made up a person to share my account with and sent the invite to another one of my email addresses. I'm not sure how long it takes for the invitation to show up to the other person's inbox (in this case mine). I've been waiting for about 30 minutes. I've checked that it's not in my spam folder. 

Browser / Chrome

OS / Window 10 Enterprise v. 1909 (OS build 18563.959)

device / ThinkPad X1 Carbon 4G

**Comment by jkhartshorne** [comment]
Which site were you using? kidtalk.app or staging.kidtalk.app?

**Comment by ythuang123** [comment]
staging.kidtalk.app -- I created a totally new/fake account following Alex's directions. He had wrote down to check whether the invite sent, and I haven't gotten anything after a couple days. I know that for the real site, I had checked and verified that the invites sent to my relatives, but that was right when we launched.

**Comment by lorenachipstudio** [comment]
@jkhartshorne @ythuang123 - We'll get this checked out in the morning and will provide updates on here. 

Thank you! 
Lorena

**Comment by lorenachipstudio** [comment]
@jkhartshorne @ythuang123 The invite was not sending because it wasn't set up to send on staging. We went ahead and turned it on so you should be able to test email invites on staging now.

**Comment by ythuang123** [comment]
Got it -- I'm confirming that it works now. I got an email invitation (in <5 minutes).

**Comment by ythuang123** [comment]
Coming back to this --> The invite email sends a link to https://kidtalk.app, not staging.kidtalk.app, so it's not easy to check whether the recording that I made on staging.kidtalk.app are shared properly (I need to go to the site directly, then get the staging cite to generate a separate link). 

Chrome / Window 10 Enterprise v. 1909 (OS build 18563.959) / ThinkPad X1 Carbon 4G

**Comment by alexchippendale** [comment]
@ythuang123 Good catch, we are working on updating the staging invite link to clear up the confusion. Thanks!

**Comment by alexchippendale** [comment]
@ythuang123 Still working on this, will update you when it's fixed.

**Comment by alexchippendale** [comment]
@ythuang123 The email link should be fixed on staging. Please confirm when you get a chance!

**Comment by ythuang123** [comment]
@alexchippendale -- Thanks the url has been fixed and it sends me to the staging site. Another problem though (ha!) -- staging doesn't seem to distinguish between folks who do and don't have record access. Instead, it always gives record access even if that box isn't checked. LMK if I've missed something. Thanks! Still using:

Chrome / Window 10 Enterprise v. 1909 (OS build 18563.959) / ThinkPad X1 Carbon 4G

**Comment by alexchippendale** [comment]
@ythuang123 Thanks for testing! Could you clear your cache and try again with a new invite? I believe it is working now. If it still doesn't would you mind closing this ticket and opening a new one with a couple screenshots? Thanks!
