### ISSUE TITLE
Start a Conversation: Waveform doesn't appear

### ISSUE THREAD

**Issue by ichimura-a** [jkhartshorne/KidTalkIssues#8]
7/31/2020
iPhone 7 / Safari / iOS 13.5.1
While recording a clip for "Start a Conversation", no orange bars for the waveform appeared. Then, the waveform did not appear when playing the clip.
I expected the waveforms to appear to be able to visualize the clip.

![IMG_6857](https://user-images.githubusercontent.com/68654587/89053225-e86d9300-d324-11ea-9df2-1d6807cd55f9.PNG)
![IMG_6858](https://user-images.githubusercontent.com/68654587/89053227-e9062980-d324-11ea-8f73-a4c7ee9bc063.PNG)
![IMG_6859](https://user-images.githubusercontent.com/68654587/89053228-e9062980-d324-11ea-99a0-2cbde7061a70.PNG)

**Comment by lorenachipstudio** [comment]
@ichimura-a Thanks for reporting- the team will take a look at it. Will follow up with updates. 

Lorena

**Comment by lorenachipstudio** [comment]
@ichimura-a Can you test this on staging? The team was not able to reproduce the bug and believe it was related to another issue that has already been fixed. Thanks so much!

**Comment by ichimura-a** [comment]
@lorenachipstudio Yes, the waveform appears for me. Thanks!
